### ISSUE TITLE
Undocumented error TF50620

### ISSUE THREAD

**Issue by hovsepk** [MicrosoftDocs/azure-devops-server-docs#66]
Hi,

Having a nightmare trying to upgrade from TFS2013 U5 to DevOps Server 2019. When I try to attach a collection database for a database that I copied over from the TFS2013U5 instance, I'm getting the following error in every collection (I have 3):

[12:41:06.937] Executing step: Set permissions for project already created
[12:41:06.937]   Executing step: 'Set permissions for project already created' AnalyticsCollection.SetProjectPermissions (2639 of 3182)
[12:41:06.943]   [Error] TF50620: The Azure DevOps identity scope 109DFB4E-21BA-4B5A-9646-A295BC5DDB7E does not exist
[12:41:06.943]   Microsoft.VisualStudio.Services.Identity.GroupScopeDoesNotExistException: TF50620: The Azure DevOps identity scope 109DFB4E-21BA-4B5A-9646-A295BC5DDB7E does not exist
[12:41:06.943]      at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.TranslateException(Int32 errorNumber, SqlException sqlException, SqlError sqlError)
[12:41:06.943]      at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.TranslateException(SqlException sqlException)
[12:41:06.943]      at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.MapException(SqlException ex, QueryExecutionState queryState)
[12:41:06.943]      at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.HandleException(Exception exception)
[12:41:06.943]      at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.ExecuteCommand(ExecuteType executeType, CommandBehavior behavior, String performanceGroupName)
[12:41:06.943]      at Microsoft.VisualStudio.Services.CircuitBreaker.Command.&lt;&gt;c__DisplayClass7_0.&lt;Execute&gt;b__0()
[12:41:06.943]      at Microsoft.VisualStudio.Services.CircuitBreaker.CommandAsync.&lt;Execute&gt;d__30.MoveNext()
[12:41:06.943]   --- End of stack trace from previous location where exception was thrown ---
[12:41:06.943]      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[12:41:06.943]      at Microsoft.VisualStudio.Services.CircuitBreaker.CommandAsync.&lt;Execute&gt;d__30.MoveNext()
[12:41:06.943]   --- End of stack trace from previous location where exception was thrown ---
[12:41:06.943]      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[12:41:06.943]      at Microsoft.VisualStudio.Services.CircuitBreaker.Command.Execute(Action run, Action fallback)
[12:41:06.943]      at Microsoft.TeamFoundation.Framework.Server.DatabaseCircuitBreaker.ExecuteCommandWithBaseCircuitBreaker(ExecuteType executeType, CommandBehavior behavior, String performanceGroupName)
[12:41:06.943]      at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.ExecuteReader()
[12:41:06.943]      at Microsoft.VisualStudio.Services.Identity.GroupComponent.QueryScopes(Guid scopeId, String scopeName)
[12:41:06.943]      at Microsoft.VisualStudio.Services.Identity.PlatformIdentityStore.GetScope(IVssRequestContext requestContext, IdentityDomain hostDomain, Guid scopeId)
[12:41:06.943]      at Microsoft.VisualStudio.Services.Identity.PlatformIdentityService.GetScope(IVssRequestContext requestContext, Guid scopeId)
[12:41:06.943]      at Microsoft.VisualStudio.Services.Identity.CompositeIdentityService.GetScope(IVssRequestContext requestContext, Guid scopeId)
[12:41:06.943]      at Microsoft.VisualStudio.Services.Analytics.AnalyticsPermission.GetProjectValidUserGroup(IVssRequestContext requestContext, Guid projectId)
[12:41:06.943]      at Microsoft.VisualStudio.Services.Analytics.AnalyticsPermission.SetAnalyticsProjectPermission(IVssRequestContext requestContext, ProjectInfo project, Func`2 shouldSetPermissionPredicate)
[12:41:06.943]      at Microsoft.VisualStudio.Services.Analytics.Extensions.AnalyticsCollectionStepPerformer.SetProjectPermissions(IVssRequestContext requestContext, ServicingContext servicingContext)
[12:41:06.943]      at Microsoft.TeamFoundation.Framework.Server.TeamFoundationStepPerformerBase.PerformHostStep(String servicingOperation, ServicingOperationTarget target, IServicingStep servicingStep, String stepData, ServicingContext servicingContext)
[12:41:06.943]      at Microsoft.TeamFoundation.Framework.Server.TeamFoundationStepPerformerBase.PerformStep(String servicingOperation, ServicingOperationTarget target, String stepType, String stepData, ServicingContext servicingContext)
[12:41:06.943]      at Microsoft.TeamFoundation.Framework.Server.ServicingStepDriver.PerformServicingStep(ServicingStep step, ServicingContext servicingContext, ServicingStepGroup group, ServicingOperation servicingOperation, Int32 stepNumber, Int32 totalSteps)
[12:41:06.943] Step failed: Set permissions for project already created. Execution time: 6 milliseconds.
[12:41:06.943]   [StepDuration] 0.0056331
[12:41:06.943]   [GroupDuration] 0.0247477
[12:41:06.943]   [OperationDuration] 0.0247715
[12:41:07.033]   Clearing dictionary, removing all items.

This issue is not documented. Many others reported that this was a bug in the earlier versions, but got resolved later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccbb0190-3faa-1d24-27c3-4653a7ff65dc
* Version Independent ID: 3a66cc20-3a18-a23e-2dbd-c211c96879d7
* Content: [Handling upgrade failures - Azure DevOps Server & TFS](https://docs.microsoft.com/en-us/azure/devops/server/troubleshooting/collection-upgrade-failure?view=azure-devops#feedback)
* Content Source: [docs/troubleshooting/collection-upgrade-failure.md](https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/blob/live/docs/troubleshooting/collection-upgrade-failure.md)
* Product: **devops-server**
* Technology: **tfs-admin**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by Tyler-H** [comment]
I encountered this error today when running the `tfsconfig ChangeServerID` console command after cloning my TFS environment. I had to run it several times to complete the changes for all different projects, but the command ultimately completed successfully, only to run into this. And when I check the web.config file in the Application Tier/Web Services/ folder, the application ID value is still unchanged.

Would really love to know how to fix this. Is it safe to just manually change the GUID value in the `applicationID` key or do I need to programmatically change it via some command or UI option?
